--1
ALTER TABLE PRODUCTOS  
MODIFY (PROD_NAME VARCHAR2(30 BYTE) );

ALTER TABLE PRODUCTOS  
MODIFY (PROD_UNIT_OF_MEASURE VARCHAR2(30 BYTE) );

ALTER TABLE PRODUCTOS  
MODIFY (PROD_STATUS VARCHAR2(30 BYTE) );


--2
ALTER TABLE PRODUCTOS 
ADD (NOMBRE VARCHAR2(50) );

ALTER TABLE PRODUCTOS 
ADD (APELLIDO VARCHAR2(50) );

COMMENT ON COLUMN PRODUCTS.NOMBRE IS 'Nombre de los vendedores';

COMMENT ON COLUMN PRODUCTS.APELLIDO IS 'Apellido de los vendedores';

--3

ALTER TABLE PRODUCTOS DROP COLUMN PROD_WEIGHT_CLASS;


--4
create table EMPLOYEES_COPY as select * from "HR"."EMPLOYEES";
 
--5
ALTER TABLE EMPLOYEES_COPY READ ONLY;

SELECT * FROM EMPLOYEES_COPY;
DELETE FROM EMPLOYEES_COPY WHERE EMPLOYEE_ID = 100;
INSERT INTO EMPLOYEES_COPY VALUES (EMPLOYEES_SEQ.NEXTVAL, 'Edison', 'Maldonado', 'ediarjc-oo@hotmail.com','0993849775',sysdate,'AD_PRES',1000,10,10,90);



CREATE TABLE PRODUCTOS (
PROD_NAME	VARCHAR2(50)	,
PROD_DESC	VARCHAR2(4000)	,
PROD_SUBCATEGORY	VARCHAR2(50)	,
PROD_SUBCATEGORY_ID	NUMBER	,
PROD_SUBCATEGORY_DESC	VARCHAR2(2000)	,
PROD_CATEGORY	VARCHAR2(50)	,
PROD_CATEGORY_ID	NUMBER	,
PROD_CATEGORY_DESC	VARCHAR2(2000)	,
PROD_WEIGHT_CLASS	NUMBER(3)	,
PROD_UNIT_OF_MEASURE	VARCHAR2(20)	,
PROD_PACK_SIZE	VARCHAR2(30)	,
SUPPLIER_ID	NUMBER(6)	,
PROD_STATUS	VARCHAR2(20)	,
PROD_LIST_PRICE	NUMBER(32)	,
PROD_MIN_PRICE	NUMBER(32)	,
PROD_TOTAL	VARCHAR2(13)	,
PROD_TOTAL_ID	NUMBER	,
PROD_SRC_ID	NUMBER	,
PROD_EFF_FROM	DATE	,
PROD_EFF_TO	DATE	,
PROD_VALID	VARCHAR2(1)	
);